### ISSUE TITLE
Paste to ix.io

### ISSUE THREAD

**Issue by Zero3K** [lordmulder/INetGet#10]
How do I do that using INetGet?

**Comment by lordmulder** [comment]
Do what? 😕

**Comment by Zero3K** [comment]
POST to that site by doing what curl -F 'f:1=<-' ix.io does.

**Comment by lordmulder** [comment]
I don't know what "that site" is, but you can create a POST request via `--verb=POST` option.

Also you can add additional data to a request (e.g. POST or PUT request) via the `--data=` option.

**See here for details:**
https://github.com/lordmulder/INetGet#options

**Comment by Zero3K** [comment]
I think it needs more options passed than the ones mentioned.

**Comment by Zero3K** [comment]
Its a pastebin alternative. I would like to know the exact commands used in order to get a paste/file's contents to show on it.

**Comment by lordmulder** [comment]
As said before, if you want to send a POST request, you need to set **`--verb=POST`** option. And, if you want to send additional "post data" (form data) along with your POST request, then option **`--data`** needs to be set accordingly. You would use that option like `--data="foo=bar&baz=quox"`.

(It is all described in the manual)

**Note:** You will have to take care about the [proper percent](https://de.wikipedia.org/wiki/URL-Encoding) encoding yourself!

For any specifics of their API, you would have to ask the author of the "a pastebin alternative" site 🤓

Regards.

**Comment by Zero3K** [comment]
How do I send a file to it or 0x0.st? Trying to use it as the URL parameter results in an error about it being an unsupported URL.

**Comment by lordmulder** [comment]
> How do I send a file to it or 0x0.st?

Sorry, I have no idea what that site is, or how it works. And I don't see why I am supposed to  figure that out for you. If you can't figure it out yourself, what about asking whoever is running the site?

----

If your question is how to read *post data* from a file with INetGet, this can be achieved as follows:
```
INetGet.exe --verb=POST --data=- http://what.ever/ output.txt < data_to_send.txt
```

(Option `--data=-` tells INetGet to read data from the *stdin*. Then we simply pass the file to *stdin*)

**Comment by Zero3K** [comment]
It uses POST but with --data-binary in the curl command line options. Is it possible to send a binary via POST when using INETGet?

**Comment by Zero3K** [comment]
It gives me a 400 error when I try to use the POST verb with 0x0.st.

**Comment by lordmulder** [comment]
> It uses POST but with --data-binary in the curl command line options. Is it possible to send a binary via POST when using INETGet?

No, not supported 😞 

Also, now that [cURL is integrated in Windows](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows), there is hardly a reason to use INetGet.

**Comment by Zero3K** [comment]
cURL crashes when I try to use it to post the file.

**Comment by lordmulder** [comment]
> cURL crashes when I try to use it to post the file.

If you can reproduce this problem, create a bug report for cURL and describe exactly how to re-produce the crash.

https://github.com/curl/curl/issues

**Comment by Zero3K** [comment]
I'd rather not.

**Comment by Zero3K** [comment]
So, someone will have to fork it and find out why I am getting the 400 error.
