### ISSUE TITLE
How do I keep a Vaughn.live stream downloading?

### ISSUE THREAD

**Issue by Zero3K** [lordmulder/INetGet#11]
When I try to download one using the latest version, it disconnects every now and then instead of just staying connected. A stream that I am trying to download using it is at https://mov3.co/en/tvtokyo/ (you can get the stream's FLV URL by using the Inspect function of any browser).

**Comment by lordmulder** [comment]
That site probably doesn't allow you to "download" the stream and will just kill your connection after a certain timeout.

Try something like [yt-dlp](https://github.com/yt-dlp/yt-dlp), if you want to rip video streams from the net...
