### ISSUE TITLE
Feature requests for it

### ISSUE THREAD

**Issue by Zero3K** [lordmulder/INetGet#6]
1.  When not specifying an output file name, it should use the name of the file that's specified in the URL (or whatever the server specifies if the URL doesn't have a file name in it) and save it in the directory that INetGet was ran in.

2. When specifying a directory along with the URL, it should use the name of the file that's specified in the URL (or whatever the server specifies if the URL doesn't have a file name in it) and save it in the directory that was specified.

**Comment by lordmulder** [comment]
There is absolutely **_no_** guarantee that the part of the URL after the last slash (**`/`**) character resembles a valid/reasonable file name. This may be the case for a lot of URLs, yes. But **_not_** in general.

Also, the server **_may_** indicate a file name via `Content-disposition:` header in the HTTP response. But this is totally _optional_, so we can **_not_** rely on it. More often than not, this header will be _absent_ from the reply.

Anyhow, if you know for sure that you are only ever going to download URLs where the last **`/`**-separated token resembles a valid file name, then it should be trivial to write up a script that "extracts" the file name from the given URL and then invokes `INetGet.exe <your_url> <filename_from_url>`.

I'm _not_ a fan of adding "features" to *INetGet* that should better be implemented in the script or application which is invoking INetGet. What you request already _can_ be done by setting the available parameters.

Remember: _"Write programs that do one thing and do it well. **Write programs to work together.**"_

Regards.

**Comment by Zero3K** [comment]
That makes sense.
