### ISSUE TITLE
Another typo in it

### ISSUE THREAD

**Issue by Zero3K** [lordmulder/INetGet#7]
"Update (replace) local file, iff server has newer version" should be "Update (replace) the local file, if the server has a newer version"

**Comment by lordmulder** [comment]
Assuming you are referring to the **`iff`**: **`iff`** is a widely-used abbreviation for **`if and only if`**.

Also lines in the help screen _should not_ exceed 80 characters – 80 characters is the "traditional" width of a terminal screen – which is why I try to save as many words as possible.

**Comment by Zero3K** [comment]
Well, I didn't know that iff was an abbreviation. Thanks for teaching me something new.
